# sync-skills.ps1 — Auto-generated by ClaudeForge setup
# Syncs skills, start.ps1, ecosystem-awareness.md across all projects
# DO NOT commit this file — it contains machine-specific paths

$SOURCE_PROJECT = "{{SOURCE_PROJECT}}"
$BASE_DIR       = "{{DEV_DIR}}"
$TEMPLATE_START = Join-Path $BASE_DIR "_templates\start.ps1"
$TEMPLATE_ECO   = Join-Path $BASE_DIR "_templates\ecosystem-awareness.md"

$projects = @(
    # Auto-populated by setup wizard
    # Add project folder names here (relative to BASE_DIR)
    # Example: "my-app", "api-server", "Trade-Bot\crypto-trading-bot"
)

Write-Host "=== Ecosystem Sync ===" -ForegroundColor Cyan
foreach ($project in $projects) {
    $targetDir = Join-Path $BASE_DIR $project
    if (-not (Test-Path $targetDir)) { Write-Host "SKIP: $project" -ForegroundColor DarkYellow; continue }
    Write-Host "--- $project ---" -ForegroundColor Yellow
    foreach ($d in @(".claude", ".claude\skills", ".claude\commands")) {
        $p = Join-Path $targetDir $d
        if (-not (Test-Path $p)) { New-Item -Path $p -ItemType Directory -Force | Out-Null }
    }
    $skillSource = Join-Path $SOURCE_PROJECT ".claude\skills"
    $skillTarget = Join-Path $targetDir ".claude\skills"
    $copied = 0
    foreach ($s in (Get-ChildItem $skillSource -Directory -ErrorAction SilentlyContinue)) {
        $dest = Join-Path $skillTarget $s.Name
        if (-not (Test-Path $dest)) { Copy-Item -Path $s.FullName -Destination $dest -Recurse -Force; $copied++ }
    }
    if (Test-Path $TEMPLATE_START) { Copy-Item $TEMPLATE_START (Join-Path $targetDir "start.ps1") -Force }
    if (Test-Path $TEMPLATE_ECO)   { Copy-Item $TEMPLATE_ECO   (Join-Path $targetDir ".claude\ecosystem-awareness.md") -Force }
    Write-Host "  skills:$copied, start.ps1:synced, ecosystem:synced" -ForegroundColor Green
}
Write-Host "=== Done ===" -ForegroundColor Cyan
